This code fails with a `NoClassDefFoundError` under Scala 3.0.0
...but it passes under Scala 2.12 & 2.13.

Scala 3 throws this error when running the code:

`java.lang.NoClassDefFoundError: com/madgag/compress/CompressUtil$`


Full stack trace:

```
[info] compiling 1 Scala source to /home/roberto/development/scala-2-vs-3-NoClassDefFoundError/target/scala-3.0.0/test-classes ...
[info] ExampleSpec:
[info] using Java Compress library
[info] com.madgag.example.ExampleSpec *** ABORTED ***
[info]   java.lang.NoClassDefFoundError: com/madgag/compress/CompressUtil$
[info]   at com.madgag.example.ExampleSpec.testFun$proxy1$1(ExampleSpec.scala:8)
[info]   at com.madgag.example.ExampleSpec.$init$$$anonfun$1(ExampleSpec.scala:8)
[info]   at org.scalatest.Transformer.apply$$anonfun$1(Transformer.scala:22)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:31)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:21)
[info]   at org.scalatest.flatspec.AnyFlatSpecLike$$anon$4.apply(AnyFlatSpecLike.scala:1697)
[info]   at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
[info]   ...
[info]   Cause: java.lang.ClassNotFoundException: com.madgag.compress.CompressUtil$
[info]   at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
[info]   at sbt.internal.ManagedClassLoader.findClass(ManagedClassLoader.java:102)
[info]   at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
[info]   at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
[info]   at com.madgag.example.ExampleSpec.testFun$proxy1$1(ExampleSpec.scala:8)
[info]   at com.madgag.example.ExampleSpec.$init$$$anonfun$1(ExampleSpec.scala:8)
[info]   at org.scalatest.Transformer.apply$$anonfun$1(Transformer.scala:22)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:31)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   ...
[error] Test suite com.madgag.example.ExampleSpec failed with java.lang.NoClassDefFoundError: com/madgag/compress/CompressUtil$.
[error] This may be due to the ClassLoaderLayeringStrategy (ScalaLibrary) used by your task.
[error] To improve performance and reduce memory, sbt attempts to cache the class loaders used to load the project dependencies.
[error] The project class files are loaded in a separate class loader that is created for each test run.
[error] The test class loader accesses the project dependency classes using the cached project dependency classloader.
[error] With this approach, class loading may fail under the following conditions:
[error]
[error]  * Dependencies use reflection to access classes in your project's classpath.
[error]    Java serialization/deserialization may cause this.
[error]  * An open package is accessed across layers. If the project's classes access or extend
[error]    jvm package private classes defined in a project dependency, it may cause an IllegalAccessError
[error]    because the jvm enforces package private at the classloader level.
[error]
[error] These issues, along with others that were not enumerated above, may be resolved by changing the class loader layering strategy.
[error] The Flat and ScalaLibrary strategies bundle the full project classpath in the same class loader.
[error] To use one of these strategies, set the  ClassLoaderLayeringStrategy key
[error] in your configuration, for example:
[error]
[error] set scala-2-vs-3-noclassdeffounderror / Test / classLoaderLayeringStrategy := ClassLoaderLayeringStrategy.ScalaLibrary
[error] set scala-2-vs-3-noclassdeffounderror / Test / classLoaderLayeringStrategy := ClassLoaderLayeringStrategy.Flat
[error]
[error] See ClassLoaderLayeringStrategy.scala for the full list of options.
```